### PR TITLE
Guzzle up to 7.x (support laravel 8.x)

### PR DESCRIPTION
**Pull request by rez1dent3**
I need a fresh guzzle to work in Laravel 8.x

### CODE REVIEW

**Comment by rez1dent3** [comment]
Resolved conflicts, let's release a fix for laravel 8+ support

**Comment by chelsEg** [comment]
> Resolved conflicts, let's release a fix for laravel 8+ support

Can you also change satooshi/php-coveralls library to php-coveralls/php-coveralls?

Because satooshi/php-coveralls library is abandoned!

**Comment by evsign** [comment]
> > Resolved conflicts, let's release a fix for laravel 8+ support
> 
> Can you also change **satooshi/php-coveralls** library to **php-coveralls/php-coveralls**?
> 
> Because **satooshi/php-coveralls** library is abandoned!

@rez1dent3 i will be glad if you are add this to the pr and then i would merge.

**Comment by rez1dent3** [comment]
@evsign I changed the package, but I don't see travis ci into repository. you can check?

**Comment by chelsEg** [comment]
> @evsign I changed the package, but I don't see travis ci into repository. you can check?

Thanks! It's very important PR!

One step to support L8 👍

**Pull request merged**
